[package]
name = "berry-api"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "api"]

[dependencies]
berry-api-api = { path = "api" }
tokio = { version = "1.45.0", features = ["full"] }
anyhow = "1.0"
