# Berry API 智能健康检查配置示例
# 演示按计费模式区分的健康检查机制

[settings]
health_check_interval_seconds = 30
request_timeout_seconds = 30
max_retries = 3
circuit_breaker_failure_threshold = 3
circuit_breaker_timeout_seconds = 60
recovery_check_interval_seconds = 120
max_internal_retries = 3
health_check_timeout_seconds = 15

# 按token计费的provider - 执行主动健康检查
[providers.openai_per_token]
name = "OpenAI Per-Token Provider"
base_url = "https://api.openai.com/v1"
api_key = "sk-your-openai-key-here"
models = ["gpt-4", "gpt-3.5-turbo"]
enabled = true
timeout_seconds = 30
max_retries = 3
billing_mode = "per_token"  # 按token计费

[providers.anthropic_per_token]
name = "Anthropic Per-Token Provider"
base_url = "https://api.anthropic.com"
api_key = "sk-ant-your-key-here"
models = ["claude-3-sonnet", "claude-3-haiku"]
enabled = true
timeout_seconds = 30
max_retries = 3
billing_mode = "per_token"  # 按token计费

# 按请求计费的provider - 跳过主动检查，使用被动验证
[providers.custom_per_request]
name = "Custom Per-Request Provider"
base_url = "https://api.custom-provider.com/v1"
api_key = "your-custom-api-key"
models = ["custom-gpt-4", "custom-claude"]
enabled = true
timeout_seconds = 30
max_retries = 3
billing_mode = "per_request"  # 按请求计费

[providers.expensive_per_request]
name = "Expensive Per-Request Provider"
base_url = "https://api.expensive-provider.com/v1"
api_key = "your-expensive-api-key"
models = ["premium-model-1", "premium-model-2"]
enabled = true
timeout_seconds = 30
max_retries = 3
billing_mode = "per_request"  # 按请求计费

# 测试provider（使用httpbin）
[providers.test_per_token]
name = "Test Per-Token Provider"
base_url = "https://httpbin.org"
api_key = "test-key"
models = ["test-model"]
enabled = true
timeout_seconds = 10
max_retries = 2
billing_mode = "per_token"

[providers.test_per_request]
name = "Test Per-Request Provider"
base_url = "https://httpbin.org"
api_key = "test-key"
models = ["test-model-pr"]
enabled = true
timeout_seconds = 10
max_retries = 2
billing_mode = "per_request"

# 智能模型映射 - 使用SmartWeightedFailover策略
[models.smart_gpt4]
name = "smart-gpt-4"
strategy = "smart_weighted_failover"  # 新的智能权重故障转移策略
enabled = true

[[models.smart_gpt4.backends]]
provider = "openai_per_token"
model = "gpt-4"
weight = 0.5  # 50%权重
priority = 1
enabled = true
tags = ["per-token", "primary"]

[[models.smart_gpt4.backends]]
provider = "custom_per_request"
model = "custom-gpt-4"
weight = 0.3  # 30%权重，不健康时降至10%，逐步恢复
priority = 2
enabled = true
tags = ["per-request", "backup"]

[[models.smart_gpt4.backends]]
provider = "expensive_per_request"
model = "premium-model-1"
weight = 0.2  # 20%权重，不健康时降至10%，逐步恢复
priority = 3
enabled = true
tags = ["per-request", "premium"]

# 混合模型 - 包含不同计费模式的provider
[models.mixed_claude]
name = "mixed-claude"
strategy = "smart_weighted_failover"
enabled = true

[[models.mixed_claude.backends]]
provider = "anthropic_per_token"
model = "claude-3-sonnet"
weight = 0.6  # 主要provider
priority = 1
enabled = true
tags = ["per-token", "primary"]

[[models.mixed_claude.backends]]
provider = "custom_per_request"
model = "custom-claude"
weight = 0.4  # 备用provider，支持权重恢复
priority = 2
enabled = true
tags = ["per-request", "backup"]

# 测试模型
[models.test_model]
name = "test-model"
strategy = "smart_weighted_failover"
enabled = true

[[models.test_model.backends]]
provider = "test_per_token"
model = "test-model"
weight = 0.7
priority = 1
enabled = true
tags = ["test", "per-token"]

[[models.test_model.backends]]
provider = "test_per_request"
model = "test-model-pr"
weight = 0.3
priority = 2
enabled = true
tags = ["test", "per-request"]

# 用户配置
[users.demo_user]
name = "Demo User"
token = "demo-token-12345"
allowed_models = ["smart-gpt-4", "mixed-claude", "test-model"]
enabled = true
tags = ["demo", "testing"]

[users.admin_user]
name = "Admin User"
token = "admin-token-67890"
allowed_models = []  # 空表示允许所有模型
enabled = true
tags = ["admin", "full-access"]
