version: '3.8'

services:
  berry-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: berry-api
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - BIND_ADDRESS=0.0.0.0:3000
      - CONFIG_PATH=/app/config.toml
    volumes:
      # 挂载配置文件
      - ./config.toml:/app/config.toml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
