name: Docker Multi-Arch Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        arch:
          - linux/amd64
          - linux/arm64

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.arch }}
          tags: ppkun00/berry-api:${{ github.ref_name }}-${{ matrix.arch }}
